[build]
  functions = "functions"
  command = "npm install"

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  external_node_modules = ["axios"]

[functions."functions/bot"]
  included_files = ["functions/bot.js"]